[versions]
bignum = "0.3.10"
compose-compiler = "1.5.0"
compose = "1.9.3"
coil = "3.0.0-rc01"
accompanist = "0.34.0"
android-gradle-plugin = "8.10.1"
core-ktx = "1.16.0"
junit = "4.13.2"
androidx-test-ext-junit = "1.2.1"
espresso-core = "3.6.1"
appcompat = "1.7.0"
material = "1.12.0"
material-icons = "1.7.8"
kotlin = "2.2.21"
kotlinStdlib = "2.2.21"
kotlinTest = "2.1.0"
runner = "1.5.2"
core = "1.7.0"
compose-plugin = "1.8.1"
kotlin-datetime = "0.7.1"
ktor = "3.0.0"
maven-publish = "0.32.0"
skiko = "0.9.4.2"
dokka = "1.9.20"
kotlinx-coroutines = "1.10.2"

scale = "1.1.1-beta.3"

[libraries]
androidx-exif = "androidx.exifinterface:exifinterface:1.4.0"

androidx-lifecycle-runtime = "androidx.lifecycle:lifecycle-runtime-ktx:2.8.7"
androidx-activity-compose = "androidx.activity:activity-compose:1.9.0"

androidx-constraintlayout-compose = "androidx.constraintlayout:constraintlayout-compose:1.1.1"
androidx-navigation-compose = "androidx.navigation:navigation-compose:2.8.9"

bignum = { module = "com.ionspin.kotlin:bignum", version.ref = "bignum" }
jvziyaoyao-origeek-ui = "com.github.jvziyaoyao:OrigeekUI:1.0.1-alpha.7"

androidx-compose-ui-util = { group = "androidx.compose.ui", name = "ui-util", version.ref = "compose" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "compose" }
androidx-compose-material = { group = "androidx.compose.material", name = "material", version.ref = "compose" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "compose" }
androidx-compose-ui-test = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "compose" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "compose" }
androidx-compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "material-icons" }

coil = { group = "io.coil-kt", name = "coil", version.ref = "coil" }
coil-gif = { group = "io.coil-kt", name = "coil-gif", version.ref = "coil" }
#coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coil-network-ktor3 = { module = "io.coil-kt.coil3:coil-network-ktor3", version.ref = "coil" }
coil-svg = { module = "io.coil-kt.coil3:coil-svg", version.ref = "coil" }

ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }

kotlinx-coroutines-swing = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }

google-accompanist-permissions = { group = "com.google.accompanist", name = "accompanist-permissions", version.ref = "accompanist" }
google-accompanist-systemuicontroller = { group = "com.google.accompanist", name = "accompanist-systemuicontroller", version.ref = "accompanist" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
junit-junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
skiko = { module = "org.jetbrains.skiko:skiko", version.ref = "skiko" }

scale-image-viewer = { group = "com.jvziyaoyao.scale", name = "image-viewer", version.ref = "scale" }
scale-image-viewer-classic = { group = "com.jvziyaoyao.scale", name = "image-viewer-classic", version.ref = "scale" }
scale-sampling-decoder = { group = "com.jvziyaoyao.scale", name = "sampling-decoder", version.ref = "scale" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlinStdlib" }
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlinTest" }
androidx-runner = { group = "androidx.test", name = "runner", version.ref = "runner" }
androidx-core = { group = "androidx.test", name = "core", version.ref = "core" }

org-jetbrains-kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlin-datetime" }

gradle-plugin-android = { module = "com.android.tools.build:gradle", version.ref = "android-gradle-plugin" }
gradle-plugin-jetbrains-compose = { module = "org.jetbrains.compose:compose-gradle-plugin", version.ref = "compose" }
gradle-plugin-compose-compiler = { module = "org.jetbrains.kotlin.plugin.compose:org.jetbrains.kotlin.plugin.compose.gradle.plugin", version.ref = "kotlin" }
gradle-plugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
gradle-plugin-maven-publish = { module = "com.vanniktech:gradle-maven-publish-plugin", version.ref = "maven-publish" }
gradle-plugin-dokka = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokka" }